spring:
  application:
    name: club-server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:club-server
    username: sa
    password:
    data: classpath:db/*
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level.root: INFO

jwt:
  token:
    header: Authorization
    issuer: ${spring.application.name}
    secret: aHdhbnNlLXNwcmluZy1zZWN1cml0eS1qd3QtYXV0aC1zZXJ2ZXItc2VjcmV0LWtleQo=
    expiration: 300
