spring:
  application:
    name: club-server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:club-server
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true